export const SET_MIDI_SEQUENCER_DATA = 'SET_MIDI_SEQUENCER_DATA';
export const SET_USER_ACCESS_TOKEN = 'SET_USER_ACCESS_TOKEN';
export const SET_USER_ID = 'SET_USER_ID';
export const USER_LOGOUT = 'USER_LOGOUT';